name: Sack
version: ${project.version}
main: drwoitschek.sack.Main
api-version: 1.15
authors: [ DrWoitschek, Internetz ]
description: Ein Sack für den Spieler

commands:
  sack:
    description: Ein Sack für den Spieler
    aliases: [ bp, backpack ]
